package com.gaotu.serialize.model.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

import com.google.protobuf.CodedInputStream;

public final class ProtoBuf {
    private ProtoBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ProtoBufExampleOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ProtoBufExample)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        String getName();

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>int32 age = 2;</code>
         *
         * @return The age.
         */
        int getAge();

        /**
         * <code>string sex = 3;</code>
         *
         * @return The sex.
         */
        String getSex();

        /**
         * <code>string sex = 3;</code>
         *
         * @return The bytes for sex.
         */
        com.google.protobuf.ByteString
        getSexBytes();

        /**
         * <code>double money = 4;</code>
         *
         * @return The money.
         */
        double getMoney();
    }

    /**
     * Protobuf type {@code ProtoBufExample}
     */
    public static final class ProtoBufExample extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ProtoBufExample)
            ProtoBufExampleOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ProtoBufExample.newBuilder() to construct.
        private ProtoBufExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ProtoBufExample() {
            name_ = "";
            sex_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ProtoBufExample(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 16: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            sex_ = s;
                            break;
                        }
                        case 33: {

                            money_ = input.readDouble();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ProtoBuf.internal_static_ProtoBufExample_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ProtoBuf.internal_static_ProtoBufExample_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ProtoBufExample.class, Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile Object name_;

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        @Override
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        @Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        /**
         * <code>int32 age = 2;</code>
         *
         * @return The age.
         */
        @Override
        public int getAge() {
            return age_;
        }

        public static final int SEX_FIELD_NUMBER = 3;
        private volatile Object sex_;

        /**
         * <code>string sex = 3;</code>
         *
         * @return The sex.
         */
        @Override
        public String getSex() {
            Object ref = sex_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                sex_ = s;
                return s;
            }
        }

        /**
         * <code>string sex = 3;</code>
         *
         * @return The bytes for sex.
         */
        @Override
        public com.google.protobuf.ByteString
        getSexBytes() {
            Object ref = sex_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                sex_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MONEY_FIELD_NUMBER = 4;
        private double money_;

        /**
         * <code>double money = 4;</code>
         *
         * @return The money.
         */
        @Override
        public double getMoney() {
            return money_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (age_ != 0) {
                output.writeInt32(2, age_);
            }
            if (!getSexBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sex_);
            }
            if (money_ != 0D) {
                output.writeDouble(4, money_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (!getSexBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sex_);
            }
            if (money_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(4, money_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ProtoBufExample)) {
                return super.equals(obj);
            }
            ProtoBufExample other = (ProtoBufExample) obj;

            if (!getName()
                    .equals(other.getName())) return false;
            if (getAge()
                    != other.getAge()) return false;
            if (!getSex()
                    .equals(other.getSex())) return false;
            if (Double.doubleToLongBits(getMoney())
                    != Double.doubleToLongBits(
                    other.getMoney())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (37 * hash) + SEX_FIELD_NUMBER;
            hash = (53 * hash) + getSex().hashCode();
            hash = (37 * hash) + MONEY_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    Double.doubleToLongBits(getMoney()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ProtoBufExample parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(CodedInputStream.newInstance(data));
        }

        public static ProtoBufExample parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(CodedInputStream.newInstance(data), extensionRegistry);
        }

        public static ProtoBufExample parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoBufExample parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoBufExample parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ProtoBufExample parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ProtoBufExample parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoBufExample parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoBufExample parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ProtoBufExample parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ProtoBufExample parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ProtoBufExample parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ProtoBufExample prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ProtoBufExample}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ProtoBufExample)
                ProtoBufExampleOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ProtoBuf.internal_static_ProtoBufExample_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ProtoBuf.internal_static_ProtoBufExample_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ProtoBufExample.class, Builder.class);
            }

            // Construct using Example.ProtoBufExample.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                name_ = "";

                age_ = 0;

                sex_ = "";

                money_ = 0D;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ProtoBuf.internal_static_ProtoBufExample_descriptor;
            }

            @Override
            public ProtoBufExample getDefaultInstanceForType() {
                return ProtoBufExample.getDefaultInstance();
            }

            @Override
            public ProtoBufExample build() {
                ProtoBufExample result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ProtoBufExample buildPartial() {
                ProtoBufExample result = new ProtoBufExample(this);
                result.name_ = name_;
                result.age_ = age_;
                result.sex_ = sex_;
                result.money_ = money_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ProtoBufExample) {
                    return mergeFrom((ProtoBufExample) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ProtoBufExample other) {
                if (other == ProtoBufExample.getDefaultInstance()) return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (!other.getSex().isEmpty()) {
                    sex_ = other.sex_;
                    onChanged();
                }
                if (other.getMoney() != 0D) {
                    setMoney(other.getMoney());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ProtoBufExample parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ProtoBufExample) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object name_ = "";

            /**
             * <code>string name = 1;</code>
             *
             * @return The name.
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int age_;

            /**
             * <code>int32 age = 2;</code>
             *
             * @return The age.
             */
            @Override
            public int getAge() {
                return age_;
            }

            /**
             * <code>int32 age = 2;</code>
             *
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            private Object sex_ = "";

            /**
             * <code>string sex = 3;</code>
             *
             * @return The sex.
             */
            public String getSex() {
                Object ref = sex_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    sex_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string sex = 3;</code>
             *
             * @return The bytes for sex.
             */
            public com.google.protobuf.ByteString
            getSexBytes() {
                Object ref = sex_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    sex_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string sex = 3;</code>
             *
             * @param value The sex to set.
             * @return This builder for chaining.
             */
            public Builder setSex(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sex_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string sex = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSex() {

                sex_ = getDefaultInstance().getSex();
                onChanged();
                return this;
            }

            /**
             * <code>string sex = 3;</code>
             *
             * @param value The bytes for sex to set.
             * @return This builder for chaining.
             */
            public Builder setSexBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                sex_ = value;
                onChanged();
                return this;
            }

            private double money_;

            /**
             * <code>double money = 4;</code>
             *
             * @return The money.
             */
            @Override
            public double getMoney() {
                return money_;
            }

            /**
             * <code>double money = 4;</code>
             *
             * @param value The money to set.
             * @return This builder for chaining.
             */
            public Builder setMoney(double value) {

                money_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double money = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMoney() {

                money_ = 0D;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ProtoBufExample)
        }

        // @@protoc_insertion_point(class_scope:ProtoBufExample)
        private static final ProtoBufExample DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ProtoBufExample();
        }

        public static ProtoBufExample getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ProtoBufExample>
                PARSER = new com.google.protobuf.AbstractParser<ProtoBufExample>() {
            @Override
            public ProtoBufExample parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ProtoBufExample(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ProtoBufExample> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ProtoBufExample> getParserForType() {
            return PARSER;
        }

        @Override
        public ProtoBufExample getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ProtoBufExample_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ProtoBufExample_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rexample.proto\"H\n\017ProtoBufExample\022\014\n\004na" +
                        "me\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\t\022\r\n\005mo" +
                        "ney\030\004 \001(\001b\006proto3"
        };
        descriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                }, (root) -> {
                    descriptor = root;
                    return null;
                });
        internal_static_ProtoBufExample_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ProtoBufExample_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ProtoBufExample_descriptor,
                new String[]{"Name", "Age", "Sex", "Money",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
